@extends('admin.layouts.app')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            Dashboard
            <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">All Clients</li>
        </ol>
        </section>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="back-bg" style="background-color:#fff; height: 64px; margin-top: 20px;">
                    @if(auth('admin')->user() && $delete_status && $delete_status =="1" )
                        <a style="margin-top: 5px; padding: 10px 17px; float: right;b margin-right: 17px;" href="#"><button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal"><i class="fa fa-file-excel-o" aria-hidden="true"></i> &nbsp; Emport xls file</button></a>
                        <a style="margin-top: 5px; padding: 10px 17px; float: right;b margin-right: 17px;" href="{{route('download-file')}}"><button type="button" class="btn btn-warning"><i class="fa fa-file-text" aria-hidden="true"></i> &nbsp; Export xls file</button></a>
                    @endif    
                </div>
            </div>
        </div>
        @if(Session::has('flash_message'))
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
          <strong>{!! session('flash_message') !!}</strong>
        </div>  
          <!-- <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em></em></div> -->
        @elseif(Session::has('flash_error'))
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
          </button>
          <strong>{!! session('flash_error') !!}</strong>
        </div>
        <!-- <div class="alert alert-danger"><span class="glyphicon glyphicon-ok"></span><em></em></div> -->
        @endif
        <!-- view list of agents -->
        <!-- Main content -->
        <section class="content">
            <table id="clients" class="stripe row-border order-column" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Client Name</th>
                        <th>Country</th>
                        <th>State</th>
                        <th>City</th>
                        <th>Proposal Date</th>
                        <th>Services</th>
                        <th>Mobile No</th>
                        <th>Email Id</th>
                        <th>Organization</th>
                        <th>Generated By</th>
                        <th>Requirement</th>
                        <th>Reference</th>
                        <th>Reminder Time</th>
                        <th>Created At</th>
                        <th>Assign BDM</th>
                        <th>Action</th>
                        
                    </tr>
                </thead>
                <tbody>
                
                    @if(!empty($clients) && isset($clients))
                        @foreach($clients as $key => $client)
                            @if($client->status== 1 || $client->status== 2 || $client->status== 3 ||$client->status== 4 || $client->status== 5 || $client->status== 6)
                                @if($client->asigned_bdm=="0")
                                    @php $bdmName =" "; @endphp
                                @else
                                    @php 
                                        $exploded = explode(',',$client->asigned_bdm);
                                        $count =  count($exploded);
                                    @endphp
                                    @if($count >= 2)
                                        @php
                                            $bdmName = $exploded[1] ? $exploded[1]:" ";
                                           
                                        @endphp
                                    @endif
                                   
                                @endif    
                            @endif
                            @php $key++;@endphp
                            @if($client->status == 0)
                            @php $bgcolor = "style='background-color:#e3ef8052;'"; @endphp
                            @elseif($client->status == 1)
                                @php $bgcolor = "style='background-color:#f3e4d1;'"; @endphp
                            @elseif($client->status == 2)
                                @php $bgcolor = "style='background-color:#fffdcabf;'"; @endphp
                            @elseif($client->status == 3)
                                @php $bgcolor = "style='background-color:#f3ec9e;'"; @endphp
                            @elseif($client->status == 4)
                                @php $bgcolor = "style='background-color:#cbe5f1;'"; @endphp
                            @elseif($client->status == 5)
                                @php $bgcolor = "style='background-color:#f1cbcb;'"; @endphp
                            @elseif($client->status == 6)
                                @php $bgcolor = "style='background-color:#80ef8352'"; @endphp
                            @endif
                            <tr <?= $bgcolor; ?>>
                                <td>{{$key}}</td>
                                <td>{{$client->client_name ? ucfirst($client->client_name): "NA" }}</td>
                                <td>{{$client->country ? ucfirst($client->country):"NA"}}</td>
                                <td>{{$client->state ? ucfirst($client->state):"NA"}}</td>
                                <td>{{$client->city ? ucfirst($client->city):"NA"}}</td>
                                <td>{{$client->proposal_date ? date('d-M-Y',strtotime($client->proposal_date)) : "NA"}} </td>
                                <td>{{$client->services ? ucfirst($client->services) : "NA"}}</td>
                                <td>{{$client->mobile_no ? $client->mobile_no : "NA"}}</td>
                                <td>{{$client->email_id ? $client->email_id : "NA"}}</td>
                                <td>{{$client->organization_name ? $client->organization_name : "NA"}}</td>
                                <td>{{$client->lead_generate_by ? ucfirst($client->lead_generate_by): "NA" }}</td>
                                <td>{{$client->requirement ? ucfirst($client->requirement):"NA"}}</td>
                                <td>{{$client->reference ? ucfirst($client->reference):"NA"}}</td>
                                <td>{{$client->reminder_time ? date('d-M-Y',strtotime($client->reminder_time)) .' At '. date('h:i ',strtotime($client->reminder_time)): "NA"}}</td>
                                <td>{{$client->created_at ? date('d-M-Y',strtotime($client->created_at)) : "NA"}}</td>
                                <td>
                                @if($client->status == 0 )
                                @php $client_id = $client->id ? $client->id:""  @endphp
                                    <select class = 'status'>
                                        <option value = " ">Select BDM </option>
                                        @foreach($all_bdm as $key => $bdm)
                                            <option value = "{{$bdm->id.'-'.$bdm->name.'-'.$client_id}}">{{$bdm->name}}</option>
                                        @endforeach 
                                    </select> 
                                @elseif($client->status == 0)
                                    <p>Follow up By {{$bdmName}}</p>
                                @elseif($client->status == 1)
                                    <p> Contacted By {{$bdmName}}</p>
                                @elseif($client->status == 2)
                                    <p>Quotation Sent By {{$bdmName}}</p>
                                @elseif($client->status == 3)
                                    <p>Negotiation By {{$bdmName}}</p>
                                @elseif($client->status == 4)
                                    <p>Important By {{$bdmName}}</p>
                                @elseif($client->status == 6)
                                    <p>Deal Done By {{$bdmName}}</p>
                                @else
                                    <p>Died By  {{$bdmName}}</p>
                                @endif    
                                    
                                </td>
                                <td>
                                @if($client->delete_status == '1')
                               
                                    <a href="{{url('all-remarks/'.encrypt($client->id).'/'.$client->delete_status)}}"><i class="fa fa-eye"style="font-size:16px;color:blue" aria-hidden="true"></i></a>&nbsp;
                                    <a href="{{url('update-live-client/'.encrypt($client->id).'/'.$client->delete_status)}}"><i class="fa fa-pencil" style="font-size:16px;color:green" aria-hidden="true"></i></a>&nbsp;
                                    <a href="{{url('delete-live-client/'.encrypt($client->id).'/'.$client->delete_status)}}"><i class="fa fa-trash" style="font-size:16px;color:red" aria-hidden="true"></i></a>&nbsp;
                                
                                @endif
                                </td>
                            </tr>
                        @endforeach 
                    @else
                    <tr>Clients not found</tr>  
                    @endif  
                </tbody> 
            </table>
        </section>    
        <!-- /.content -->
    </div>
    <!-- modal open for import file -->
   
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Import Bulk Data</h4>
                </div>
                <div class="modal-body">
                {!! Form::open(['url' => 'import-file','enctype'=>'multipart/form-data']) !!}
                    {{ Form::file('file',['class'=>' ']) }}   
                </div>
                <div class="modal-footer">
                    {{ Form::submit('Submit',['class'=>'btn btn-success']) }}
                    {{ Form::button('Cancel',['class'=>'btn btn-default','data-dismiss'=>'modal']) }}
                {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    <!-- modal close -->
@endsection
@section('script')
<script>
 
    $(document).ready(function() {
        var table = $('#clients').removeAttr('width').DataTable({
            scrollY:        "400px",
            scrollX:        true,
            scrollCollapse: true,
            paging:         true,
            columnDefs: [
                { width: 200 }
            ],
            fixedColumns: true
        });
    });

    // select bdm
    
    $(".status").change(function () {
        var data = this.value;
        
        $.ajax({
            type:'post',
            url: "{{URL::route('asign-bdm')}}",
            data:{'data':data,"_token": "{{ csrf_token() }}"},
            dataType:'json',
            success: function(result){
                if(result.status=='error'){
                    alert(result.message);
                }else{
                    alert(result.message);
                    location.reload();
                }   
            }
        });    
    });
</script>
@endsection	
 
